### ISSUE TITLE
Weapon level and object is not reset when restarting game

### ISSUE THREAD

**Issue by keatonfs** [raza6/24rogue#3]
When you click the restart button, the game continues to use the past game's weapon because currentWeapon is not reset to 0. This means that the text reads that I am using a knife or battle-axe, but I am using a weapon with the stats of a stick. I have made the changes on a local branch but I don't have permissions to create a branch and push for a PR.

**Comment by raza6** [comment]
Hi, thanks for bringing that up ! I think you can do a pull request by [forking](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) the project first.
